Traceback (most recent call last):
  File "/home/eric/jb_reports/.venv/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/eric/jb_reports/.venv/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eric/jb_reports/.venv/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/eric/jb_reports/.venv/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/eric/jb_reports/.venv/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/eric/jb_reports/.venv/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# load data
df = pd.read_pickle('../../mydata/yjbg_y2022_profit.pkl.gz')
code = pd.read_pickle('../../mydata/ashare_basic.pkl.gz')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[3], line 2[0m
[1;32m      1[0m [38;5;66;03m# load data[39;00m
[0;32m----> 2[0m df [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mread_pickle[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m../../mydata/yjbg_y2022_profit.pkl.gz[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      3[0m code [38;5;241m=[39m pd[38;5;241m.[39mread_pickle([38;5;124m'[39m[38;5;124m../../mydata/ashare_basic.pkl.gz[39m[38;5;124m'[39m)

File [0;32m~/jb_reports/.venv/lib/python3.12/site-packages/pandas/io/pickle.py:185[0m, in [0;36mread_pickle[0;34m(filepath_or_buffer, compression, storage_options)[0m
[1;32m    123[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m    124[0m [38;5;124;03mLoad pickled pandas object (or any object) from file.[39;00m
[1;32m    125[0m 
[0;32m   (...)[0m
[1;32m    182[0m [38;5;124;03m4    4    9[39;00m
[1;32m    183[0m [38;5;124;03m"""[39;00m
[1;32m    184[0m excs_to_catch [38;5;241m=[39m ([38;5;167;01mAttributeError[39;00m, [38;5;167;01mImportError[39;00m, [38;5;167;01mModuleNotFoundError[39;00m, [38;5;167;01mTypeError[39;00m)
[0;32m--> 185[0m [38;5;28;01mwith[39;00m [43mget_handle[49m[43m([49m
[1;32m    186[0m [43m    [49m[43mfilepath_or_buffer[49m[43m,[49m
[1;32m    187[0m [43m    [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m    188[0m [43m    [49m[43mcompression[49m[38;5;241;43m=[39;49m[43mcompression[49m[43m,[49m
[1;32m    189[0m [43m    [49m[43mis_text[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m,[49m
[1;32m    190[0m [43m    [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m[43m,[49m
[1;32m    191[0m [43m[49m[43m)[49m [38;5;28;01mas[39;00m handles:
[1;32m    192[0m     [38;5;66;03m# 1) try standard library Pickle[39;00m
[1;32m    193[0m     [38;5;66;03m# 2) try pickle_compat (older pandas version) to handle subclass changes[39;00m
[1;32m    194[0m     [38;5;66;03m# 3) try pickle_compat with latin-1 encoding upon a UnicodeDecodeError[39;00m
[1;32m    196[0m     [38;5;28;01mtry[39;00m:
[1;32m    197[0m         [38;5;66;03m# TypeError for Cython complaints about object.__new__ vs Tick.__new__[39;00m
[1;32m    198[0m         [38;5;28;01mtry[39;00m:

File [0;32m~/jb_reports/.venv/lib/python3.12/site-packages/pandas/io/common.py:765[0m, in [0;36mget_handle[0;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[1;32m    761[0m [38;5;28;01mif[39;00m compression [38;5;241m==[39m [38;5;124m"[39m[38;5;124mgzip[39m[38;5;124m"[39m:
[1;32m    762[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(handle, [38;5;28mstr[39m):
[1;32m    763[0m         [38;5;66;03m# error: Incompatible types in assignment (expression has type[39;00m
[1;32m    764[0m         [38;5;66;03m# "GzipFile", variable has type "Union[str, BaseBuffer]")[39;00m
[0;32m--> 765[0m         handle [38;5;241m=[39m [43mgzip[49m[38;5;241;43m.[39;49m[43mGzipFile[49m[43m([49m[43m  [49m[38;5;66;43;03m# type: ignore[assignment][39;49;00m
[1;32m    766[0m [43m            [49m[43mfilename[49m[38;5;241;43m=[39;49m[43mhandle[49m[43m,[49m
[1;32m    767[0m [43m            [49m[43mmode[49m[38;5;241;43m=[39;49m[43mioargs[49m[38;5;241;43m.[39;49m[43mmode[49m[43m,[49m
[1;32m    768[0m [43m            [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcompression_args[49m[43m,[49m
[1;32m    769[0m [43m        [49m[43m)[49m
[1;32m    770[0m     [38;5;28;01melse[39;00m:
[1;32m    771[0m         handle [38;5;241m=[39m gzip[38;5;241m.[39mGzipFile(
[1;32m    772[0m             [38;5;66;03m# No overload variant of "GzipFile" matches argument types[39;00m
[1;32m    773[0m             [38;5;66;03m# "Union[str, BaseBuffer]", "str", "Dict[str, Any]"[39;00m
[0;32m   (...)[0m
[1;32m    776[0m             [38;5;241m*[39m[38;5;241m*[39mcompression_args,
[1;32m    777[0m         )

File [0;32m/usr/lib/python3.12/gzip.py:192[0m, in [0;36mGzipFile.__init__[0;34m(self, filename, mode, compresslevel, fileobj, mtime)[0m
[1;32m    190[0m     mode [38;5;241m+[39m[38;5;241m=[39m [38;5;124m'[39m[38;5;124mb[39m[38;5;124m'[39m
[1;32m    191[0m [38;5;28;01mif[39;00m fileobj [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 192[0m     fileobj [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mmyfileobj [38;5;241m=[39m [43mbuiltins[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mmode[49m[43m [49m[38;5;129;43;01mor[39;49;00m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m    193[0m [38;5;28;01mif[39;00m filename [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    194[0m     filename [38;5;241m=[39m [38;5;28mgetattr[39m(fileobj, [38;5;124m'[39m[38;5;124mname[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m'[39m)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../../mydata/yjbg_y2022_profit.pkl.gz'

